name: flutter_sanity_client
description: Dart libary to query the Sanity.io API. Supports running queries and downloading files.
version: 1.2.0
homepage: https://github.com/bkazula/flutter_sanity_client
repository: https://github.com/bkazula/flutter_sanity_client

environment:
  sdk: ">=3.2.5 <4.0.0"
dependencies:
  http: ^1.1.0
dev_dependencies:
  test: ^1.20.2
